services:
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
    #Replace the password and users with something real
      MARIADB_ROOT_PASSWORD: asdf
      MARIADB_DATABASE: tmdb
      MARIADB_USER: test
      MARIADB_PASSWORD: asdf  
    restart: always
    build: 
      context: .
    ports:
      - "3306:3306"
    volumes:
      - deeplinkdata:/var/lib/mysql
volumes:
  deeplinkdata: