services:
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
    #Replace the password and users with something real
      MARIADB_ROOT_PASSWORD: asdf
      MARIADB_DATABASE: tmdb
      MARIADB_USER: test
      MARIADB_PASSWORD: asdf  
      MASTER_HOST: host_location
      MASTER_USER: test
      MASTER_PASSWORD: asdf
      MASTER_LOG_FILE: 'mysql-bin.000001'
      MASTER_LOG_POS: 4
    restart: always
    build: 
      context: .
    ports:
      - "3306:3306"
    volumes:
      - deeplinkdata:/var/lib/mysql
volumes:
  deeplinkdata: